package njuics.demos.petsalon.controller;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.*;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.Resource;
import org.springframework.hateoas.Resources;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import njuics.demos.petsalon.model.Owner;
import njuics.demos.petsalon.repository.OwnerRepository;

@RestController
@RequestMapping(path="/owners") // This means URL's start with /owners
public class OwnerController {
	@Autowired // This means to get the bean called repository
               // Which is auto-generated by Spring, we will use it to handle the data
	private OwnerRepository repository;

	@PostMapping(path="")
	public @ResponseBody String addNewOwner (@RequestBody Owner owner) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		repository.save(owner);
		return "New Owner Saved";
	}
	
	@GetMapping(path="")
	public @ResponseBody 
	Resources<Resource<Owner>> getAllOwners() {
		// 先将 repository.findAll() 从 Iterable<> 转换为 List<>
		Iterable<Owner> ownersIt = repository.findAll();
		List<Owner> ownersLs = new ArrayList<>();
		ownersIt.forEach(i -> { ownersLs.add(i); });
		
		List<Resource<Owner>> owners = ownersLs.stream().map(
				owner -> new Resource<>(owner, 
						linkTo(methodOn(OwnerController.class).getOneOwner(owner.getId())).withSelfRel(),
						linkTo(methodOn(OwnerController.class).getAllOwners()).withRel("owners")
						)
				).collect(Collectors.toList());
		
		return new Resources<>(owners, linkTo(methodOn(OwnerController.class).getAllOwners()).withSelfRel());
	}
	
	@GetMapping("/{id}")
	public @ResponseBody 
	Resource<Owner> getOneOwner(@PathVariable Integer id) {
		Owner owner = repository.findById(id)
				.orElseThrow(() -> new RuntimeException());

		return new Resource<>(owner,
			linkTo(methodOn(OwnerController.class).getOneOwner(id)).withSelfRel(),
			linkTo(methodOn(OwnerController.class).getAllOwners()).withRel("owners"));
	}
	
	@PutMapping("/{id}")
	public Owner replaceOwner(@RequestBody Owner newOwner, @PathVariable Integer id) {
		
		return repository.findById(id)
			.map(owner -> {
				owner.setName(newOwner.getName());
				return repository.save(owner);
			})
			.orElseGet(() -> {
				newOwner.setId(id);
				return repository.save(newOwner);
			});
	}

	@DeleteMapping("/{id}")
	public @ResponseBody String deleteOwner(@PathVariable Integer id) {
		repository.deleteById(id);
		return "Deleted";
	}
}