package njuics.demos.petsalon.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;

import njuics.demos.petsalon.model.Pet;
import njuics.demos.petsalon.repository.PetRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/pets") // This means URL's start with /pets
public class PetController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PetRepository petRepository;

	@PostMapping(path="/add")
	public @ResponseBody String addNewPet (@RequestBody Pet pet) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		petRepository.save(pet);
		return "New Pet Saved";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Pet> getAllPets() {
		// This returns a JSON or XML
		return petRepository.findAll();
	}
}
